# Generated by Django 4.0.10 on 2023-07-15 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_users', '0018_allow_operator_view_organisation'),
        ('firmware_upgrader', '0008_firmware_image_baseurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openwisp_users.organization', verbose_name='organization'),
        ),
    ]
